App\Entity\Cake:
  type: entity
  repositoryClass: App\Repository\CakeRepository

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    name:
      type: string

    description:
      type: text

    price:
      type: string

    image:
      type: string

    createdAt:
      type: datetime

  manyToMany:
    categories:
      targetEntity: App\Entity\Category
      joinTable:
        name: cake_category
        joinColumns:
          cake_id:
            referencedColumnName: id
        inversedJoinColumns:
          category_id:
            referencedColumnName: id
